<?php

namespace Database\Seeders;

use App\Models\JobApplicationField;
use Illuminate\Database\Seeder;

class JobApplicationFieldsSeeder extends Seeder
{
    public function run(): void
    {
        $fields = [
            [
                'label' => 'Full Name',
                'field_key' => 'full_name',
                'field_type' => 'text',
                'placeholder' => 'Enter your full name',
                'help_text' => 'Please enter your name exactly as in passport.',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 1,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Phone Number',
                'field_key' => 'phone_number',
                'field_type' => 'text',
                'placeholder' => 'Enter your phone number',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 2,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'WhatsApp Number',
                'field_key' => 'whatsapp_number',
                'field_type' => 'text',
                'placeholder' => 'Enter your WhatsApp number',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 3,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Email Address',
                'field_key' => 'email',
                'field_type' => 'text',
                'placeholder' => 'Enter your email address',
                'help_text' => 'Use a valid email address.',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 4,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Nationality',
                'field_key' => 'nationality',
                'field_type' => 'select',
                'placeholder' => null,
                'help_text' => 'Select your nationality.',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 5,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Current Location',
                'field_key' => 'current_location',
                'field_type' => 'text',
                'placeholder' => 'Enter your current location',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 6,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Years of Experience',
                'field_key' => 'experience',
                'field_type' => 'text',
                'placeholder' => 'Enter your years of experience',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 7,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Current Job Title',
                'field_key' => 'job_title',
                'field_type' => 'text',
                'placeholder' => 'Enter your current job title',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 8,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Notice Period / Availability',
                'field_key' => 'availability',
                'field_type' => 'text',
                'placeholder' => 'Enter your availability',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 9,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Brief Summary of Experience',
                'field_key' => 'summary',
                'field_type' => 'textarea',
                'placeholder' => 'Write a brief summary of your experience',
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 10,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'Upload Your Certificates (if Any)',
                'field_key' => 'certificates',
                'field_type' => 'file',
                'placeholder' => null,
                'help_text' => 'Optional: upload certificates if available.',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 11,
                'is_global' => true,
                'field_group' => 'additional',
            ],
            [
                'label' => 'Upload Your CV',
                'field_key' => 'cv_file',
                'field_type' => 'file',
                'placeholder' => null,
                'help_text' => 'Upload your updated CV.',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 12,
                'is_global' => true,
                'field_group' => 'basic',
            ],
            [
                'label' => 'test',
                'field_key' => 'test',
                'field_type' => 'checkbox',
                'placeholder' => null,
                'help_text' => null,
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 13,
                'is_global' => true,
                'field_group' => 'additional',
            ],
            [
                'label' => 'maximo cert',
                'field_key' => 'maximo_cert',
                'field_type' => 'checkbox',
                'placeholder' => null,
                'help_text' => null,
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 14,
                'is_global' => true,
                'field_group' => 'additional',
            ],
        ];

        foreach ($fields as $field) {
            JobApplicationField::updateOrCreate(
                ['field_key' => $field['field_key']],
                array_merge($field, ['job_id' => null]),
            );
        }
    }
}