deployment:
  tasks:
    - export APPPATH=/home/sfcoly/erp-system
    - export PUBLICPATH=/home/sfcoly/erp

    - /bin/cp artisan $APPPATH/artisan
    - /bin/cp composer.json $APPPATH/composer.json
    - /bin/cp composer.lock $APPPATH/composer.lock

    - /bin/rm -rf $APPPATH/app && /bin/cp -R app $APPPATH
    - /bin/rm -rf $APPPATH/bootstrap && /bin/cp -R bootstrap $APPPATH
    - /bin/rm -rf $APPPATH/config && /bin/cp -R config $APPPATH
    - /bin/rm -rf $APPPATH/database && /bin/cp -R database $APPPATH
    - /bin/rm -rf $APPPATH/resources && /bin/cp -R resources $APPPATH
    - /bin/rm -rf $APPPATH/routes && /bin/cp -R routes $APPPATH

    - /bin/cp public/.htaccess $PUBLICPATH/.htaccess || true
    - /bin/cp public/favicon.ico $PUBLICPATH/favicon.ico || true
    - /bin/cp public/robots.txt $PUBLICPATH/robots.txt || true

    - /bin/rm -rf $PUBLICPATH/build && /bin/cp -R public/build $PUBLICPATH || true
    - /bin/rm -rf $PUBLICPATH/images && /bin/cp -R public/images $PUBLICPATH || true
    - /bin/rm -rf $PUBLICPATH/fonts && /bin/cp -R public/fonts $PUBLICPATH || true
    - /bin/rm -rf $PUBLICPATH/js && /bin/cp -R public/js $PUBLICPATH || true
    - /bin/rm -rf $PUBLICPATH/css && /bin/cp -R public/css $PUBLICPATH || true

    - /bin/echo "<?php

use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

if (file_exists(\$maintenance = '/home/sfcoly/erp-system/storage/framework/maintenance.php')) {
    require \$maintenance;
}

require '/home/sfcoly/erp-system/vendor/autoload.php';

\$app = require_once '/home/sfcoly/erp-system/bootstrap/app.php';

\$app->handleRequest(Request::capture());" > /home/sfcoly/erp/index.php

    - php /home/sfcoly/erp-system/artisan optimize:clear || true