deployment:
  tasks:
    - export APPPATH=/home/sfcoly/erp-system
    - export PUBLICPATH=/home/sfcoly/erp

    - /bin/cp artisan $APPPATH/artisan
    - /bin/cp composer.json $APPPATH/composer.json
    - /bin/cp composer.lock $APPPATH/composer.lock

    - /bin/rm -rf $APPPATH/app
    - /bin/cp -R app $APPPATH/app

    - /bin/rm -rf $APPPATH/bootstrap
    - /bin/cp -R bootstrap $APPPATH/bootstrap

    - /bin/rm -rf $APPPATH/config
    - /bin/cp -R config $APPPATH/config

    - /bin/rm -rf $APPPATH/database
    - /bin/cp -R database $APPPATH/database

    - /bin/rm -rf $APPPATH/resources
    - /bin/cp -R resources $APPPATH/resources

    - /bin/rm -rf $APPPATH/routes
    - /bin/cp -R routes $APPPATH/routes

    - /bin/cp public/.htaccess $PUBLICPATH/.htaccess || true
    - /bin/cp public/favicon.ico $PUBLICPATH/favicon.ico || true
    - /bin/cp public/robots.txt $PUBLICPATH/robots.txt || true

    - /bin/rm -rf $PUBLICPATH/build
    - /bin/cp -R public/build $PUBLICPATH/build || true

    - /bin/rm -rf $PUBLICPATH/images
    - /bin/cp -R public/images $PUBLICPATH/images || true

    - /bin/rm -rf $PUBLICPATH/fonts
    - /bin/cp -R public/fonts $PUBLICPATH/fonts || true

    - /bin/rm -rf $PUBLICPATH/js
    - /bin/cp -R public/js $PUBLICPATH/js || true

    - /bin/rm -rf $PUBLICPATH/css
    - /bin/cp -R public/css $PUBLICPATH/css || true

    - php /home/sfcoly/erp-system/artisan migrate --force || true
    - /opt/cpanel/composer/bin/composer dump-autoload -o -d /home/sfcoly/erp-system || true
    - php /home/sfcoly/erp-system/artisan optimize:clear || true
    - php /home/sfcoly/erp-system/artisan optimize || true